version: '2'

services:
  zookeeper:
    image: dockerkafka/zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
      - "5000:5000"
    networks:
      - sky-net

  kafka:
    image: dockerkafka/kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    links:
      - zookeeper
    networks:
      - sky-net

networks:
  sky-net:
    driver: bridge